spring.application.name=cinstar
server.port=8081



spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


themoviedb.url.showing=https://api.themoviedb.org/3/movie/now_playing?language=vi&page=1
themoviedb.url.main=https://api.themoviedb.org/3/movie/
a=http://image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg
redis.host=localhost
redis.port=6379

allowed.origin=http://localhost:3000/

